CREATE DATABASE IF NOT EXISTS phpmyadmin
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'pma'@'%' IDENTIFIED BY 'root' REQUIRE SSL;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX
ON phpmyadmin.* TO 'pma'@'%';

FLUSH PRIVILEGES;
